### ISSUE TITLE
Проверить ДЗ №5 по курсу Jmix : homework-developing-user-interface (TICKETS)

### ISSUE THREAD

**Issue by urjadovaa** [urjadovaa/jmix-homework-developing-user-interface#1]

**Comment by glebfox** [comment]
**FlightBrowse**

`<groupBox id="filterBox">` - ширину стоит сделать 100%, чтобы рамка была по ширине экрана, а внутренние компоненты обернуть в hbox, чтобы они были поджаты друг к другу.

**TicketReservation**

для элемента `<layout>` стоит задать свойство `spacing="true"`

**Comment by urjadovaa** [comment]
Замечания устранены.
